---
  - import_role:
      name: ansible-network.network-engine

  - name: "TASK 1: GET COMMAND OUTPUT"
    ios_command:
      commands:
        - show cdp neighbors
    register: lldp_outpu  
  - name: "TASK 2: RUN THROUGH THE PARSER"
    textfsm_parser:
      file: "~/ntc-templates/templates/cisco_ios_show_lldp_neighbors.textfsm"
      content: "{{ cdp_output.stdout[0] }}"
      name: cdp_outpu  
  - name: "TASK 3: SHOW ANSIBLE FACTS OUTPUT"
    debug:
      msg: "{{ ansible_facts }} "

  - name: "TASK 4: PRINT NEIGHBORS FROM ANSIBLE NETWORK ENGINE"
    debug:
      msg: "{{ item['LOCAL_INTERFACE'] }}: {{ item['NEIGHBOR'] }}"
    loop: "{{ ansible_facts[cdp_output'] }}"
    loop_control:
      label: "{{ item['LOCAL_INTERFACE'] }}"